// This file is auto-generated by the Supabase CLI and will be overwritten

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      scorecard: {
        Row: {
          id: string
          player_id: string
          name: string
          score: number | null
          hole_number: number | null
          event_id: string
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string
          player_id: string
          name: string
          score?: number | null
          hole_number?: number | null
          event_id: string
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          player_id?: string
          name?: string
          score?: number | null
          hole_number?: number | null
          event_id?: string
          created_at?: string | null
          updated_at?: string | null
        }
      }
      leaderboard_snapshot: {
        Row: {
          id: string
          event_id: string
          time_filter: string
          scores: Json | null
          last_updated: string | null
        }
        Insert: {
          id?: string
          event_id: string
          time_filter: string
          scores?: Json | null
          last_updated?: string | null
        }
        Update: {
          id?: string
          event_id?: string
          time_filter?: string
          scores?: Json | null
          last_updated?: string | null
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
